-- CreateTable
CREATE TABLE "CATEGORIA" (
    "ID" SERIAL NOT NULL,
    "NOMBRE" VARCHAR(80) NOT NULL,

    CONSTRAINT "CATEGORIA_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "SERVICIO" (
    "ID" SERIAL NOT NULL,
    "DESCRIPCION" VARCHAR(200) NOT NULL,
    "CATEGORIA_ID" INTEGER NOT NULL,

    CONSTRAINT "SERVICIO_pkey" PRIMARY KEY ("ID")
);

-- AddForeignKey
ALTER TABLE "SERVICIO" ADD CONSTRAINT "SERVICIO_CATEGORIA_ID_fkey" FOREIGN KEY ("CATEGORIA_ID") REFERENCES "CATEGORIA"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
