-- CreateTable
CREATE TABLE "ROL" (
    "ID" SERIAL NOT NULL,
    "NOMBRE" VARCHAR(100) NOT NULL,

    CONSTRAINT "ROL_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "PERMISO" (
    "ID" SERIAL NOT NULL,
    "NOMBRE" VARCHAR(100) NOT NULL,

    CONSTRAINT "PERMISO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "ROL_PERMISO" (
    "ID_PERMISO" INTEGER NOT NULL,
    "ID_ROL" INTEGER NOT NULL,

    CONSTRAINT "ROL_PERMISO_pkey" PRIMARY KEY ("ID_PERMISO","ID_ROL")
);

-- CreateTable
CREATE TABLE "USUARIO" (
    "ID" SERIAL NOT NULL,
    "USERNAME" VARCHAR(30) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "EMAIL" VARCHAR(30) NOT NULL,
    "ID_ROL" INTEGER,

    CONSTRAINT "USUARIO_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "USUARIO_USERNAME_key" ON "USUARIO"("USERNAME");

-- CreateIndex
CREATE UNIQUE INDEX "USUARIO_EMAIL_key" ON "USUARIO"("EMAIL");

-- AddForeignKey
ALTER TABLE "ROL_PERMISO" ADD CONSTRAINT "ROL_PERMISO_ID_PERMISO_fkey" FOREIGN KEY ("ID_PERMISO") REFERENCES "PERMISO"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROL_PERMISO" ADD CONSTRAINT "ROL_PERMISO_ID_ROL_fkey" FOREIGN KEY ("ID_ROL") REFERENCES "ROL"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USUARIO" ADD CONSTRAINT "USUARIO_ID_ROL_fkey" FOREIGN KEY ("ID_ROL") REFERENCES "ROL"("ID") ON DELETE CASCADE ON UPDATE CASCADE;
