-- CreateEnum
CREATE TYPE "ESTADO_PROFORMA" AS ENUM ('PENDIENTE', 'APROBADA', 'RECHAZADA', 'COMPLETADA');

-- CreateTable
CREATE TABLE "PROFORMA" (
    "ID" BIGSERIAL NOT NULL,
    "FECHA" DATE NOT NULL,
    "ESTADO" "ESTADO_PROFORMA" NOT NULL DEFAULT 'PENDIENTE',
    "TOTAL" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "CLIENTE_CI" INTEGER NOT NULL,
    "DIAGNOSTICO_ID" BIGINT,

    CONSTRAINT "PROFORMA_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "PROFORMA_REPUESTO" (
    "ID" SERIAL NOT NULL,
    "NOMBRE" VARCHAR(120) NOT NULL,
    "PROFORMA_ID" BIGINT NOT NULL,

    CONSTRAINT "PROFORMA_REPUESTO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "DETALLE_PROFORMA" (
    "ID" BIGSERIAL NOT NULL,
    "PROFORMA_ID" BIGINT NOT NULL,
    "SERVICIO_ID" INTEGER,
    "DESCRIPCION" VARCHAR(250) NOT NULL,
    "CANTIDAD" DECIMAL(10,2) NOT NULL,
    "PRECIO_UNIT" DECIMAL(12,2) NOT NULL,
    "SUBTOTAL" DECIMAL(12,2) NOT NULL,

    CONSTRAINT "DETALLE_PROFORMA_pkey" PRIMARY KEY ("ID","PROFORMA_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "PROFORMA_DIAGNOSTICO_ID_key" ON "PROFORMA"("DIAGNOSTICO_ID");

-- AddForeignKey
ALTER TABLE "PROFORMA" ADD CONSTRAINT "PROFORMA_CLIENTE_CI_fkey" FOREIGN KEY ("CLIENTE_CI") REFERENCES "CLIENTE"("CI") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROFORMA" ADD CONSTRAINT "PROFORMA_DIAGNOSTICO_ID_fkey" FOREIGN KEY ("DIAGNOSTICO_ID") REFERENCES "DIAGNOSTICO"("NRO") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROFORMA_REPUESTO" ADD CONSTRAINT "PROFORMA_REPUESTO_PROFORMA_ID_fkey" FOREIGN KEY ("PROFORMA_ID") REFERENCES "PROFORMA"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DETALLE_PROFORMA" ADD CONSTRAINT "DETALLE_PROFORMA_PROFORMA_ID_fkey" FOREIGN KEY ("PROFORMA_ID") REFERENCES "PROFORMA"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DETALLE_PROFORMA" ADD CONSTRAINT "DETALLE_PROFORMA_SERVICIO_ID_fkey" FOREIGN KEY ("SERVICIO_ID") REFERENCES "SERVICIO"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
