-- CreateTable
CREATE TABLE "EMPLEADO" (
    "CI" INTEGER NOT NULL,
    "ID_USUARIO" INTEGER,
    "NOMBRE" VARCHAR(15) NOT NULL,
    "APELLIDOS" VARCHAR(50) NOT NULL,
    "DIRECCION" VARCHAR(70) NOT NULL,
    "FECHANAC" DATE NOT NULL,
    "TELEFONO" VARCHAR(10) NOT NULL,

    CONSTRAINT "EMPLEADO_pkey" PRIMARY KEY ("CI")
);

-- CreateIndex
CREATE UNIQUE INDEX "EMPLEADO_ID_USUARIO_key" ON "EMPLEADO"("ID_USUARIO");

-- AddForeignKey
ALTER TABLE "EMPLEADO" ADD CONSTRAINT "EMPLEADO_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID") ON DELETE SET NULL ON UPDATE CASCADE;
