-- CreateTable
CREATE TABLE "BITACORA" (
    "ID_BITACORA" BIGSERIAL NOT NULL,
    "USUARIO_ID" INTEGER NOT NULL,
    "DESCRIPCION" TEXT NOT NULL,
    "FECHA_HORA" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "IP_ORIGEN" VARCHAR(45),

    CONSTRAINT "BITACORA_pkey" PRIMARY KEY ("ID_BITACORA")
);

-- AddForeignKey
ALTER TABLE "BITACORA" ADD CONSTRAINT "BITACORA_USUARIO_ID_fkey" FOREIGN KEY ("USUARIO_ID") REFERENCES "USUARIO"("ID") ON DELETE CASCADE ON UPDATE CASCADE;
