-- CreateTable
CREATE TABLE "MARCA_MOTO" (
    "ID" SERIAL NOT NULL,
    "NOMBRE" TEXT NOT NULL,

    CONSTRAINT "MARCA_MOTO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "MOTO" (
    "PLACA" VARCHAR(10) NOT NULL,
    "MODELO" TEXT NOT NULL,
    "AÑO" SMALLINT NOT NULL,
    "CHASIS" TEXT,
    "MARCA_ID" INTEGER NOT NULL,

    CONSTRAINT "MOTO_pkey" PRIMARY KEY ("PLACA")
);

-- CreateIndex
CREATE UNIQUE INDEX "MOTO_CHASIS_key" ON "MOTO"("CHASIS");

-- AddForeignKey
ALTER TABLE "MOTO" ADD CONSTRAINT "MOTO_MARCA_ID_fkey" FOREIGN KEY ("MARCA_ID") REFERENCES "MARCA_MOTO"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
