-- CreateTable
CREATE TABLE "DIAGNOSTICO" (
    "NRO" BIGSERIAL NOT NULL,
    "FECHA" DATE NOT NULL,
    "HORA" TIME NOT NULL,
    "PLACA_MOTO" VARCHAR(10) NOT NULL,
    "EMPLEADO_CI" INTEGER NOT NULL,

    CONSTRAINT "DIAGNOSTICO_pkey" PRIMARY KEY ("NRO")
);

-- CreateTable
CREATE TABLE "DETALLE_DIAGNOSTICO" (
    "ID" BIGSERIAL NOT NULL,
    "DIAGNOSTICO_ID" BIGINT NOT NULL,
    "DESCRIPCION" TEXT NOT NULL,

    CONSTRAINT "DETALLE_DIAGNOSTICO_pkey" PRIMARY KEY ("ID","DIAGNOSTICO_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "DIAGNOSTICO_PLACA_MOTO_FECHA_HORA_key" ON "DIAGNOSTICO"("PLACA_MOTO", "FECHA", "HORA");

-- AddForeignKey
ALTER TABLE "DIAGNOSTICO" ADD CONSTRAINT "DIAGNOSTICO_PLACA_MOTO_fkey" FOREIGN KEY ("PLACA_MOTO") REFERENCES "MOTO"("PLACA") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DIAGNOSTICO" ADD CONSTRAINT "DIAGNOSTICO_EMPLEADO_CI_fkey" FOREIGN KEY ("EMPLEADO_CI") REFERENCES "EMPLEADO"("CI") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DETALLE_DIAGNOSTICO" ADD CONSTRAINT "DETALLE_DIAGNOSTICO_DIAGNOSTICO_ID_fkey" FOREIGN KEY ("DIAGNOSTICO_ID") REFERENCES "DIAGNOSTICO"("NRO") ON DELETE CASCADE ON UPDATE CASCADE;
