-- CreateTable
CREATE TABLE "MARCA_HERRAMIENTA" (
    "ID" SERIAL NOT NULL,
    "NOMBRE" VARCHAR(100) NOT NULL,

    CONSTRAINT "MARCA_HERRAMIENTA_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "HERRAMIENTA" (
    "ID" SERIAL NOT NULL,
    "NOMBRE" VARCHAR(120) NOT NULL,
    "DESCRIPCION" VARCHAR(250),
    "MARCA_ID" INTEGER NOT NULL,

    CONSTRAINT "HERRAMIENTA_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "MOVIMIENTO_HERRAMIENTA" (
    "HERRAMIENTA_ID" INTEGER NOT NULL,
    "ORDEN_TRABAJO_ID" INTEGER NOT NULL,
    "FECHA" DATE NOT NULL,
    "CANTIDAD" INTEGER NOT NULL,

    CONSTRAINT "MOVIMIENTO_HERRAMIENTA_pkey" PRIMARY KEY ("ORDEN_TRABAJO_ID","HERRAMIENTA_ID")
);

-- AddForeignKey
ALTER TABLE "HERRAMIENTA" ADD CONSTRAINT "HERRAMIENTA_MARCA_ID_fkey" FOREIGN KEY ("MARCA_ID") REFERENCES "MARCA_HERRAMIENTA"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MOVIMIENTO_HERRAMIENTA" ADD CONSTRAINT "MOVIMIENTO_HERRAMIENTA_HERRAMIENTA_ID_fkey" FOREIGN KEY ("HERRAMIENTA_ID") REFERENCES "HERRAMIENTA"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MOVIMIENTO_HERRAMIENTA" ADD CONSTRAINT "MOVIMIENTO_HERRAMIENTA_ORDEN_TRABAJO_ID_fkey" FOREIGN KEY ("ORDEN_TRABAJO_ID") REFERENCES "orden_trabajo"("id") ON DELETE CASCADE ON UPDATE CASCADE;
