-- CreateTable
CREATE TABLE "CLIENTE" (
    "CI" INTEGER NOT NULL,
    "NOMBRE" TEXT NOT NULL,
    "APELLIDOS" TEXT NOT NULL,
    "TELEFONO" TEXT NOT NULL,
    "DIRECCION" TEXT NOT NULL,

    CONSTRAINT "CLIENTE_pkey" PRIMARY KEY ("CI")
);
